version: "3.7"
services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hipersend
      - POSTGRES_PASSWORD=hipersend
      - POSTGRES_DB=hipersend_database
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: hipersend_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
